easy_admin:
    entities:
        # change the following to the namespaces of your own entities
        - AppBundle\Entity\OrderItem
        - AppBundle\Entity\Orders
        - AppBundle\Entity\User
        - AppBundle\Entity\Device
        - AppBundle\Entity\Mobile
        - AppBundle\Entity\Hoover
        - AppBundle\Entity\Freezer