app:
    resource: '@AppBundle/Resources/config/routing.yml'

api:
    resource: api_routes.yml
    type: rest
    prefix: /api/

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin