app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: api_routes.yml
    type: rest
    prefix: /api/

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin


#users:
#    type:     rest
#    resource: AppBundle\Controller\UsersController