AppBundle\Entity\Device:
  type: entity
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: discr
    type: string
  discriminatorMap:
    device: Device
    mobile: Mobile
    hoover: Hoover
    freezer: Freezer
  table: device
  repositoryClass: AppBundle\Repository\DeviceRepository
  id:
      id:
          type: smallint
          nullable: false
          options:
              unsigned: true
          id: true
          generator:
              strategy: AUTO
  fields:
      firm:
          type: string
          nullable: false
      price:
          type: float
          precision: 19
          scale: 2
          nullable: false
      color:
           type: string
           nullable: false
