AppBundle\Entity\Orders:
    type: entity
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        create_date:
            type: datetime
        updated_date:
            type: datetime
        total_qty:
            type: integer
        total_price:
            type: decimal
            precision: 19
            scale: 2
        order_items:
            type: text