AppBundle\Entity\OrderItem:
    type: entity
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        price:
            type: decimal
            precision: 19
            scale: 2
